import Link from "next/link";

export const metadata = {
  title: {
    absolute: "",
    default: "This is the default title",
    template: "%s | NextJs",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "#7F27FF", padding: "1rem" }}>
          <h2>Navigation Links</h2>

          <div className="flex flex-row">
            <Link href="/blogs">Blog</Link>
            <Link href="/dashboard">Dashboard</Link>
            <Link href="/products">Products</Link>
            <Link href="/profile">Profile</Link>
          </div>
        </header>
        {children}
        <footer style={{ backgroundColor: "#9F70FD", padding: "2rem" }}>
          FOOTER
        </footer>
      </body>
    </html>
  );
}
